// Mock data used only for visual development when the backend is offline.
// The app always prefers real API responses and only falls back to these
// when a network error occurs, so it stays API-ready.

export const mockAnnouncements = [
  {
    A_ID: 1,
    title: "CodeSprint 2026 — National Coding Challenge",
    category: "Competition",
    deadline: "2026-09-24",
    event_date: "2026-09-28",
    department: "Computer Science",
    topic: "Competitive Programming",
    source: "Placement Cell",
    important_link: "https://example.com/codesprint",
    requirements: "Team of 2, current student ID, GitHub account",
    notes: "Register on the portal before the deadline. Prizes for top 3 teams.",
  },
  {
    A_ID: 2,
    title: "HackTheNorth Hackathon",
    category: "Hackathon",
    deadline: "2026-10-05",
    event_date: "2026-10-12",
    department: "IT",
    topic: "AI & Web",
    source: "Innovation Club",
    important_link: "https://example.com/hackthenorth",
    requirements: "Team of 4",
    notes: "48-hour hackathon. Meals provided.",
  },
  {
    A_ID: 3,
    title: "Cloud Foundations Workshop",
    category: "Workshop",
    deadline: null,
    event_date: "2026-09-30",
    department: "Information Technology",
    topic: "Cloud Computing",
    source: "AWS Educate",
    important_link: null,
    requirements: "Laptop with AWS account",
    notes: "Hands-on session on EC2, S3, and IAM.",
  },
  {
    A_ID: 4,
    title: "Summer Internship — Backend Developer",
    category: "Internship",
    deadline: "2026-09-20",
    event_date: null,
    department: "Placement Cell",
    topic: "Software Engineering",
    source: "TechCorp",
    important_link: "https://example.com/internship",
    requirements: "Python, MySQL, basic Docker",
    notes: "6-week paid internship. Remote friendly.",
  },
  {
    A_ID: 5,
    title: "Mid-Semester Examination Notice",
    category: "Exam",
    deadline: "2026-09-15",
    event_date: "2026-09-25",
    department: "Examination Section",
    topic: "Academics",
    source: "Controller of Examinations",
    important_link: "https://example.com/exam-schedule",
    requirements: "Hall ticket and student ID",
    notes: "Seating arrangements posted on the notice board.",
  },
  {
    A_ID: 6,
    title: "Data Structures Assignment 3",
    category: "Assignment",
    deadline: "2026-09-22",
    event_date: null,
    department: "Computer Science",
    topic: "Data Structures",
    source: "Prof. A. Sharma",
    important_link: null,
    requirements: "Submit PDF via LMS",
    notes: "Late submissions penalized 10% per day.",
  },
  {
    A_ID: 7,
    title: "Merit Scholarship 2026",
    category: "Scholarship",
    deadline: "2026-10-10",
    event_date: null,
    department: "Scholarship Cell",
    topic: "Financial Aid",
    source: "College Administration",
    important_link: "https://example.com/scholarship",
    requirements: "CGPA > 8.0, family income certificate",
    notes: "Covers 50% tuition for one academic year.",
  },
  {
    A_ID: 8,
    title: "On-Campus Placement Drive — FinServe",
    category: "Placement",
    deadline: "2026-09-18",
    event_date: "2026-09-23",
    department: "Placement Cell",
    topic: "Final Placements",
    source: "FinServe Technologies",
    important_link: "https://example.com/finserv-drive",
    requirements: "2026 batch, no active backlogs",
    notes: "Package: 12 LPA. Three rounds: OA, technical, HR.",
  },
];

export function findMockAnnouncement(id) {
  return mockAnnouncements.find((a) => String(a.A_ID) === String(id)) || null;
}

export const mockProfile = {
  P_ID: 1,
  name: "Aarav Patel",
  email: "aarav.patel@college.edu",
  username: "aarav_p",
  year: "Third Year",
  college: "National Institute of Technology",
  stream: "Computer Science",
  preferences: "Hackathon, Internship, Placement",
};

export const mockBookmarks = mockAnnouncements.slice(0, 3);
